config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "chats#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get "list", to: "chats#list", as: :list

  resources :chats do
    resources :messages, only: [:new, :create]
  end

  resources :stareds, only: [:index, :show, :create, :destroy]
  get 'profile', to: 'users#show', as: :user

  get 'yourchats', to: 'chats#list_by_user', as: :yourchats
  get 'createdchats', to: 'chats#created_by_user', as: :createdchats

  resources :joined_chats, only: [:create]

  # devise_scope :user do
  #   delete '/users/sign_out', to: 'devise/sessions#destroy'
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  # user.picture_url
  has_many :joined_chats
  has_many :chats, through: :joined_chats
  has_many :messages
  has_many :stareds

  after_commit :broadcast_user_status, on: [:update]

  private

  def broadcast_user_status
    return unless saved_change_to_online?
    partial_data = self.compute_online_user_num_on_chat
    Rails.logger.error "...........................#{partial_data}"
    broadcast_update_to "presence",
                        partial: "chats/my_chats_online_users",
                        target: "joined-tab-pane",
                        locals: {chats_with_messages_count: partial_data}
  end

  def compute_online_user_num_on_chat
    my_messages = Message.where(user_id: self.id)
    chats = self.chats
    my_messages.each do |my_message|
      unless chats.include?(my_message.chat)
        chats.push(my_message.chat)
      end
    end
    chats_with_messages_count = []
    # Select all message that message.user.online = true

    messages = Message.includes(:user).where(user: {online: true})
    # Remove repeatted messages
    seen = Set.new
    now_ele_arr = messages.select do |item|
      identifier = "#{item['user_id']}_#{item['chat_id']}"
      unless seen.include?(identifier)
        seen.add(identifier)
      end
    end
    # Count the num by chat_id
    counts = Hash.new(0)
    now_ele_arr.each do |item|
      value = item.chat_id
      counts[value] = [] unless counts.has_key?(value)
      counts[value] << item.user
    end
    # counts.as_json

    online_num = counts.to_h
    chats.each_with_index do |chat, index|
      chats_with_messages_count[index] = chat.attributes.dup
      chats_with_messages_count[index]["msgcount"] = Message.where(chat_id: chat.id).count
      online_num.keys.each do |key|
        if chats_with_messages_count[index]['id'] == key
          chats_with_messages_count[index]["online_num"] = online_num[key]
        end
      end
    end
    chats_with_messages_count
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    super
    current_user.update(online: true)
    sleep(1)
  end

  def destroy
    current_user.update(online: false)
    sleep(1)
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    params[:username]
  end

  def destroy
    sign_out(current_user)
      redirect_to root_path, notice: "You have successfully logged out."
  end

  def show
    @user = current_user
    #redirect_to list_path
    @chats = if params[:query].present?
        Chat.search_by_title_and_synopsis(params[:query])
      else
        Chat.all
      end
  end

  def mark_offline
    current_user.update(online: false)
    head :ok
  end
end

app/views/users/show.html.erb
<div><%= render "shared/searchbar" %></div>

<div class="profile-image-container">
  <%= cl_image_tag @user.photo.key,  transformation: [
    {aspect_ratio: "1.0", width: 150, crop: "fill"},
    {radius: "max"},
    {fetch_format: "auto"}
    ]%>
</div>

<div class="row w-100 user-profile">
  <div class="col-12 mb-4">
    <div class="card user-card">
      <div class="card-body">
        <h6 class="username"><%= current_user.username.to_s.capitalize %></h6>
        <h6 class="full-name"><%= current_user.name.to_s.capitalize + " " + current_user.last_name.to_s.capitalize %></h6>
        <h6 class="email"><%= current_user.email %></h6>
      </div>
    </div>
  </div>
</div>

<div class="button-container">
  <%= link_to "My Chats", yourchats_path, class: "btn btn-secondary" %>
</div>
<br>
<div class="button-container">
  <%= link_to "Starred", stareds_path, class: "btn btn-secondary" %>
  <%# path will be changed according to chats created by me page %>
</div>
<br>
<div class="button-container">
  <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
</div>