config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "chats#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get "list", to: "chats#list", as: :list

  resources :chats do
    resources :messages, only: [:new, :create]
  end

  resources :stareds, only: [:index, :show, :create, :destroy]
  get 'profile', to: 'users#show', as: :user

  get 'yourchats', to: 'chats#list_by_user', as: :yourchats
  get 'createdchats', to: 'chats#created_by_user', as: :createdchats

  resources :joined_chats, only: [:create]

  # devise_scope :user do
  #   delete '/users/sign_out', to: 'devise/sessions#destroy'
  # end

end

app/models/chat.rb
class Chat < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :joined_chats, dependent: :destroy

  pg_search_scope :search_by_title_and_synopsis,
    against: [:title, :category, :description, :location],
    using: {
    tsearch: { prefix: true }
  }
  has_many :messages
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)
    @chat.user = current_user

    if @chat.save
      redirect_to list_path(@chat), notice: "Your group chas has been succesfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new

    if current_user.chats.include?(@chat)
      @joined = true
    else
      @joined = false
    end
  end

  def list_by_user
    unless params[:query].present?
      my_messages = Message.where(user_id: current_user.id)

      # to get the chats we clicked 'join' for
      chats = current_user.chats

      # to get the chats we have written a message in
      my_messages.each do |my_message|
        unless chats.include?(my_message.chat)
          chats.push(my_message.chat)
        end
      end

      # @chats = User.find(current_user.id).chats
      @chats_with_messages_count = []
      online_num = compute_online_user_num_on_chat.to_h
      chats.each_with_index do |chat, index|
        @chats_with_messages_count[index] = chat.attributes.dup
        @chats_with_messages_count[index]["msgcount"] = Message.where(chat_id: chat.id).count
        online_num.keys.each do |key|
          if @chats_with_messages_count[index]['id'] == key
            @chats_with_messages_count[index]["online_num"] = online_num[key]
          end
        end
      end
    else
      list
    end


    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.append(:joined-tab-pane, partial: "chats/my_chats_online_users",
          target: "joined-tab-pane",
          locals: { chats_with_messages_count: @chats_with_messages_count })
      end
      format.html do
        if request.path != yourchats_path
          redirect_to yourchats_path
        end
      end
    end
    @created_chats = Chat.where(user_id: current_user.id)
  end

  def list
    @user = current_user
    @chats = Chat.all
    if params[:query].present?
      @chats = Chat.search_by_title_and_synopsis(params[:query])
    else
      @chats = Chat.all
    end
  end

  def created_by_user
    @created_chats = Chat.where(user_id: current_user.id)
  end


  private

  def chat_params
    params.require(:chat).permit(:title, :category, :description)
  end

  def compute_online_user_num_on_chat
      # Select all message that message.user.online = true
      messages = Message.includes(:user).where(user: {online: true})
      # Remove repeatted messages
      seen = Set.new
      now_ele_arr = messages.select do |item|
        identifier = "#{item['user_id']}_#{item['chat_id']}"
        unless seen.include?(identifier)
          seen.add(identifier)
        end
      end
      # Count the num by chat_id
      counts = Hash.new(0)
      now_ele_arr.each do |item|
        value = item.chat_id
        counts[value] = [] unless counts.has_key?(value)
        counts[value] << item.user
      end
      counts
  end
end

app/views/chats/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banner.jpg')%>);">
  <div class="container">
    <h1><strong>ExpatUs</strong></h1>
    <p>Find your community</p>
  </div>
</div>

app/views/chats/_created_by_user.html.erb
<h1 class="title">Chats I Created</h1>

<div class="row w-100">
      <% @chats.each do |chat| %>
        <div class="col-12 mb-4">
          <%= link_to chat_path(chat), style: "text-decoration: none; color: inherit;" do %>
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= chat.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= chat.category %></h6>
                <p class="card-text"><%= chat.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/chats/_footer.html.erb
<div class="footer">
    <%= link_to image_tag('chats.png', class: "footer-icon"), current_user ? yourchats_path : root_path %>
    <%= link_to image_tag('home.png', class: "footer-icon"), current_user ? list_path : root_path %>
    <%= link_to image_tag('avatar.png', class: "footer-icon"), current_user ? user_path : root_path %>
</div>

app/views/chats/_form.html.erb
<div class="simple-form">
  <%= simple_form_for(@chat) do |f| %>
    <div class="input">
      <%= f.input :title %>
      <%= f.input :category, :collection => [:Life, :Job, :Social, :Shopping, :Housing, :Language, :Food, :Legal] %>
      <%= f.input :description %>
      <p><%= f.submit "Create Chat", class: "btn btn-secondary" %></p>
    </div>
  <% end %>
</div>

app/views/chats/_join.html.erb
<%= button_to "#{@joined ? 'Joined!' : 'Join'}", '#', method: :post, remote: true, class: "btn btn-secondary join-btn", data: { controller: 'join-button', chat_id: @chat.id, action: "click->join-button#join" }, disabled: @joined %>

app/views/chats/_my_chats_online_users.html.erb
<ul class="list-unstyled mb-0 mt-2" id="my-chats-online-users">
<% if chats_with_messages_count.present? %>
  <% chats_with_messages_count.each_with_index do |chat, index| %>
    <li>
      <div class="d-flex align-items-center justify-content-between">
          <div>
              <p class="mb-0">
                <a href="/chats/<%= chat['id']%>"><%= chat['title'] %></a>
              </p>
              <div id="online-users-list"></div>
              <p class="mb-0">
                <span class="badge bg-success-transparent" id="online-users-list-<%= chat['id'] %>"><%= chat['online_num'].present?? chat['online_num'].length : 0 %> Online</span>
              </p>
          </div>
          <div class="avatar-list-stacked my-auto" id="online-users-list-avatar-<%= chat['id'] %>">
            <% if chat['online_num'].present?%>
              <% chat['online_num'].each do |user| %>
                <span class="avatar avatar-sm avatar-rounded">
                  <%= cl_image_tag user.photo.key %>
                </span>
              <% end %>
            <%end%>
            <a href="/chats/<%= chat['id']%>" class="avatar avatar-sm bg-primary text-fixed-white avatar-rounded"><%= "+#{chat['msgcount']}" %></a>
          </div>
      </div>
    </li>
  <% end %>
<% else %>
  <p class="fs-11 fw-semibold mb-1 op-7">You haven't joined any chat group yet.</p>
<% end %>
</ul>

app/views/chats/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "avatar.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Chats", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/chats/created_by_user.html.erb
<h1 class="title">Chats I Created</h1>

<div class="row w-100">
      <% @chats.each do |chat| %>
        <div class="col-12 mb-4">
          <%= link_to chat_path(chat), style: "text-decoration: none; color: inherit;" do %>
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= chat.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= chat.category %></h6>
                <p class="card-text"><%= chat.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/chats/index.html.erb
<div><%= render "banner" %></div>


<div class="description">
  <p>Find group chats that match your needs and interests —or create ones that make you feel at home</p>
</div>

<div class="button-container">
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-secondary" %>
  <%= link_to "Log In", user_session_path, class: "btn btn-secondary" %>
</div>

app/views/chats/list.html.erb
<div class="containter">

<div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banner.jpg')%>);
     background-size: cover;
     background-position: center;
     background-repeat: no-repeat;">
   <%= render "shared/searchbar" %>
  <h1 class="title">Welcome Home <%= current_user.username.to_s.capitalize %> </h1>
<br>
</div>
<h3 class="title">Trending Chats</h3>
      <div class="button-container">
      <%= link_to "Create a Chat", new_chat_path(@chat), class: "btn btn-secondary" %>
    </div>
    <br>
  <div class="container d-flex flex-column align-items-center">
    <div class="row w-100">
    <% if @chats.present? %>
      <% @chats.reverse.each do |chat| %>
        <div class="col-12 mb-2 mt-4">
          <%= link_to chat_path(chat), style: "text-decoration: none; color: inherit;" do %>
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= chat.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= chat.category %></h6>
                <p class="card-text"><%= chat.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <% else %>
      <h5>There are no chats with <%= params[:query] %>. You can create one!</h5>
    <% end %>
    </div>

  </div>
</div>

app/views/chats/list_by_user.html.erb
<div class="main-content app-content">

  <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banner.jpg')%>);
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;">
    <div><%= render "shared/searchbar" %></div>
    <h1 class="title">My Chats</h1>
    <br>
  </div>
  <br>
  <div class="button-container">
    <%= link_to "Create a Chat", new_chat_path(@chat), class: "btn btn-secondary" %>
  </div>
  <br>
  <div class="container-fluid">
    <div class="main-chart-wrapper p-2 gap-2 d-lg-flex">
      <div class="chat-info">
        <ul class="nav nav-tabs tab-style-2 nav-justified mb-0 d-flex" id="myTab1" role="tablist">
          <!-- <li class="nav-item border-end me-0" role="presentation">
            <button class="nav-link active h-100" id="users-tab" data-bs-toggle="tab"
                data-bs-target="#users-tab-pane" type="button" role="tab"
                aria-controls="users-tab-pane" aria-selected="true">
                <i class="ri-history-line me-1 align-middle d-inline-block"></i>Recent
            </button>
          </li>-->
          <li class="nav-item me-0" role="presentation">
            <button class="nav-link active h-100" id="joined-tab" data-bs-toggle="tab" data-bs-target="#joined-tab-pane"
              type="button" role="tab" aria-controls="joined-tab-pane" aria-selected="true">
              <i class="ri-group-2-line me-1 align-middle d-inline-block"></i>Joined
            </button>
          </li>
          <li class="nav-item me-0" role="presentation">
            <button class="nav-link" id="created-tab" data-bs-toggle="tab" data-bs-target="#created-tab-pane"
              type="button" role="tab" aria-controls="created-tab-pane" aria-selected="false">
              <i class="ri-group-2-line me-1 align-middle d-inline-block"></i>Created
            </button>
          </li>
        </ul>

        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="joined-tab-pane" role="tabpanel" aria-labelledby="joined-tab">
            <%= render "chats/my_chats_online_users", chats_with_messages_count: @chats_with_messages_count %>
          </div>
          <div class="tab-pane fade" id="created-tab-pane" role="tabpanel" aria-labelledby="created-tab">
            <ul class="list-unstyled mb-0 mt-2">
              <% if @created_chats.present? %>
                <% @created_chats.each_with_index do |chat, index| %>
                  <li>
                    <div class="d-flex align-items-center justify-content-between">
                      <div>
                        <p class="mb-0"><%= link_to chat.title, chat_path(chat) %></p>
                        <p class="mb-0">
                          <span class="badge bg-success-transparent" id="online-users-list-<%= chat['id'] %>">
                        <%= 1 %> Online
                      </span>
                        </p>
                      </div>
                      <div class="avatar-list-stacked my-auto">
                        <span class="avatar avatar-sm avatar-rounded">
                          <%= image_tag "faces/22.png" %> <!-- Replace with dynamic avatars if needed -->
                        </span>
                        <%= link_to "+#{chat.messages.count}", chat_path(chat), class: "avatar avatar-sm bg-primary text-fixed-white avatar-rounded" %>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <p class="fs-11 fw-semibold mb-1 op-7">You haven't created any chat groups yet.</p>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<h1 class="title">Create your group</h1>

<div>
  <%= link_to image_tag('back.png', class: "back-button"), list_path %>
</div>

<%= render "form" %>

app/views/chats/search_empty.html.erb
<div class="containter">

<div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banner.jpg')%>);
     background-size: cover;
     background-position: center;
     background-repeat: no-repeat;">
   <%= render "shared/searchbar" %>
  <h1 class="title">Welcome Home <%= current_user.username.to_s.capitalize %> </h1>
<br>
</div>
<h3 class="title">Trending Chats</h3>
      <div class="button-container">
      <%= link_to "Create a Chat", new_chat_path(@chat), class: "btn btn-secondary" %>
    </div>
    <br>

<div>
<h4><%= "#{params[:query]} have not been found. You can create a new group for it!" %></h4>
</div>
</div>

app/views/chats/show.html.erb
<div>
  <%= link_to image_tag('back.png', class: "back-button", style: "margin-top: 15px;"), yourchats_path %>
</div>

<div class="container chat">
<%= render "chats/join" if current_user != @chat.user %>
<div>
  <h4 style="margin-top: 20px; margin-bottom: 10px; color: #5E9C6B"><%= @chat.title %></h4>
</div>
  <%= turbo_stream_from "chat_#{@chat.id}_messages" %>
  <div id="messages" class="messages ">
    <% @chat.messages.each do |message| %>
      <%= render "messages/message", message: message, user: current_user  %>
    <% end %>
  </div>


  <%= simple_form_for [@chat, @message],
    html: {class: "d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }} do |f|
  %>
    <% #other_user = current_user == @chat.user ? @chat.user : @chat.message.user %>
    <%= f.input :content,
      label: false,
      placeholder: "Message",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>
</div>